services:
  db:
    container_name: postgres
    image: postgres
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver:
      bridge
volumes:
  db:


